kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  web-redirect-uri: ${KAKAO_WEB_REDIRECT_URL}
  ios-redirect-uri: ${KAKAO_IOS_REDIRECT_URL}
application:
  jwt:
    refresh-exp: ${REFRESH_EXP}
    access-exp: ${ACCESS_EXP}
    prefix: Bearer
    header: Authorization
    secretKey: ${SECRET_KEY}
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  datasource:
    url: ${MY_SQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MY_SQL_USER}
    password: ${MY_SQL_PW}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html